---
services:
  ansible:
    build: ansible/control
    image: suckowbiz/ansible
    depends_on:
      - "ansible-base"
  ansible-base:
    build: ansible/base
    image: suckowbiz/ansible-base
  ansible-playbook:
    build: ansible/playbook
    image: suckowbiz/ansible-playbook
    depends_on:
      - "ansible-base"
  ansible-vault:
    build: ansible/vault
    image: suckowbiz/ansible-vault
    depends_on:
      - "ansible-base"
  clementine:
    build: clementine
    image: suckowbiz/clementine
  gimp:
    build: gimp
    image: suckowbiz/gimp
  goland:
    build: goland
    image: suckowbiz/goland
