---
version: '3'
services:
  ansible:
    build: ansible/control
    image: suckowbiz/ansible
    depends_on:
      - "ansible-base"
  ansible-base:
    build: ansible/base
    image: suckowbiz/ansible-base
  ansible-playbook:
    build: ansible/playbook
    image: suckowbiz/ansible-playbook
    depends_on:
      - "ansible-base"
  ansible-vault:
    build: ansible/vault
    image: suckowbiz/ansible-vault
    depends_on:
      - "ansible-base"
  caddy:
    build: caddy
    image: suckowbiz/caddy
  clementine:
    build: clementine
    image: suckowbiz/clementine
  code:
    build: code
    image: suckowbiz/code
  chrome:
    build: chrome
    image: suckowbiz/chrome
  chromix:
    build: chromix
    image: suckowbiz/chromix
    depends_on:
      - "chrome"
  gimp:
    build: gimp
    image: suckowbiz/gimp
  goland:
    build: goland
    image: suckowbiz/goland
  keepass2:
    build: keepass2
    image: suckowbiz/keepass2
  logster:
    build: logster
    image: suckowbiz/logster
  nginx:
    build: nginx/base
    image: suckowbiz/nginx
  nginx-php:
    build: nginx/php
    image: suckowbiz/nginx-php
    depends_on:
      - "nginx"
  supertux:
    build: supertux
    image: suckowbiz/supertux
  tor:
    build: tor
    image: suckowbiz/tor
  unifi:
    build: unifi
    image: suckowbiz/unifi