#!/usr/bin/env bash
#
# Runs Docker container as stated below.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='caddy'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"
readonly CADDYFILE="${PWD}/Caddyfile"
readonly CADDYPATH="${PWD}/.caddy"


# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

if [[ ! -f "${CADDYFILE}" ]]; then
    echo "${CADDYFILE} must not be an absent file."
    exit 1
fi

if [[ ! -d "${CADDYPATH}" ]]; then
    echo "${CADDYFILE} must not be an absent directory."
    exit 1
fi

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run \
  --detach \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --publish 2015:2015 \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume "${CADDYFILE}":/var/lib/caddy/Caddyfile:ro \
  --volume "${CADDYPATH}":/var/lib/caddy/.caddy \
  "${IMAGE_NAME}" "$@"
