#!/usr/bin/env bash
#
# Runs Docker container as stated below.
set -e
readonly IMAGE_NAME='suckowbiz/vscode'
readonly CONTAINER_NAME='code'

readonly GIT_CONFIG="${HOME}/.gitconfig"
mkdir --parents \
    "${USERDATA_ROOT:=${HOME}/.config/vscode/userdata}" \
    "${EXTENSIONS_ROOT:=${HOME}/.config/vscode/extensions}" \

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Visual%20Studio%20Code%0A
cat <<EOH

╦  ╦┬┌─┐┬ ┬┌─┐┬    ╔═╗┌┬┐┬ ┬┌┬┐┬┌─┐  ╔═╗┌─┐┌┬┐┌─┐
╚╗╔╝│└─┐│ │├─┤│    ╚═╗ │ │ │ ││││ │  ║  │ │ ││├┤ 
 ╚╝ ┴└─┘└─┘┴ ┴┴─┘  ╚═╝ ┴ └─┘─┴┘┴└─┘  ╚═╝└─┘─┴┘└─┘
${IMAGE_NAME}

========
Volumes:
========
Code......: '${PWD}'
Extensions: '${EXTENSIONS_ROOT}'
Git Config: '${GIT_CONFIG}'
User Data.: '${USERDATA_ROOT}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm -f -v ${CONTAINER_NAME} >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# Code` \
  --ipc=host \
  --privileged \
  --volume "${EXTENSIONS_ROOT}":/opt/vscode/extensions \
  --volume "${GIT_CONFIG}":/opt/git/.gitconfig \
  --volume "${PWD}":/Code \
  --volume "${USERDATA_ROOT}":/opt/vscode/userdata \
  ${IMAGE_NAME} "$@")
echo "${CONTAINER_ID}"
