#!/usr/bin/env bash
#
# Run Intellij Goland Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly IMAGE_NAME='suckowbiz/goland'
readonly CONTAINER_NAME='goland'

readonly GIT_CONFIG="${HOME}/.gitconfig"
mkdir --parent \
  "${PROJECTS_DIR:=${HOME}/GoLandProjects}" \
  "${GOLAND_DIR:=${HOME}/.GoLand}" \
  "${SSH_DIR:=${HOME}/.ssh}" \
  "${JAVA_DIR:=${HOME}/.java}" || true

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Goland
cat <<EOH

╔═╗┌─┐┌─┐┬  ┌─┐┌┐┌┌┬┐
║ ╦│ ││ ┬│  ├─┤│││ ││
╚═╝└─┘└─┘┴─┘┴ ┴┘└┘─┴┘
$IMAGE_NAME

=======
Volumes:
=======
Goland Settings: '${GOLAND_DIR}'
Java Settings...: '${JAVA_DIR}'
Projects........: '${PROJECTS_DIR}'
SSH Settings....: '${SSH_DIR}'
Git config......: '${GIT_CONFIG}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run \
  --detach \
  --env DISPLAY \
  --env GIVEN_GROUP="$(id -gn "${USER}")" \
  --env GIVEN_GROUP_ID="$(id -g "${USER}")" \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --net=host \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume "${GIT_CONFIG}":/opt/.gitconfig \
  --volume "${GOLAND_DIR}":/opt/.GoLand \
  --volume "${JAVA_DIR}":/opt/.java \
  --volume "${PROJECTS_DIR}":/opt/GoLandProjects \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  ${IMAGE_NAME}
