#!/usr/bin/env bash
#
# Run Intellij Goland in a Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly IMAGE_NAME='suckowbiz/goland'
readonly CONTAINER_NAME='goland'

# Update local copy with latest remote version.
docker pull ${IMAGE_NAME}

# Increase inode count to speed up file watches.
sudo sysctl -w fs.inotify.max_user_watches=524288

readonly BASE_CONF="${HOME}/.config"
mkdir --parent \
  "${GIT_CONF:=${BASE_CONF}/GoLand/gitconfig}" \
  "${GOPATH:=${HOME}/go}" \
  "${GOLAND_CONF:=${BASE_CONF}/GoLand}" \
  "${JAVA_CONF:=${BASE_CONF}/GoLand/java}" || true
touch "${GIT_CONF}/.gitconfig"

SSH_PATH=""
if [[ -L "${HOME}/.ssh" ]]; then
  readonly possiblePath=$(readlink -f "${HOME}/.ssh")
  if [[ -d "${possiblePath}" ]]; then
    SSH_PATH=$possiblePath
  fi
elif [[ -d "${HOME}/.ssh" ]]; then
  SSH_PATH="${HOME}/.ssh"
fi


# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Goland
cat <<EOH

╔═╗┌─┐┬  ┌─┐┌┐┌┌┬┐
║ ╦│ ││  ├─┤│││ ││
╚═╝└─┘┴─┘┴ ┴┘└┘─┴┘
$IMAGE_NAME

========
Volumes:
========
Docker Socket...: '/var/run/docker.sock'
GoLand Conf.....: '${GOLAND_CONF}'
GoLand Java Conf: '${JAVA_CONF}'
GOPATH..........: '${GOPATH}'
Git Conf........: '${GIT_CONF}'
SSH ............: '${SSH_PATH}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

SSH_CONF_VOLUME=""
if [[ ! "${SSH_PATH}" = "" ]]; then
  SSH_CONF_VOLUME="--volume ${SSH_PATH}:/volume/.ssh"
fi

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP="$(id -gn "${USER}")" \
  --env GIVEN_GROUP_ID="$(id -g "${USER}")" \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --env HOST_GROUP=hostdocker \
  --env HOST_GROUP_ID="$(cut -d: -f3 < <(getent group docker))" \
  `# Goland` \
  --security-opt=seccomp:unconfined `# allow ptrace etc which is required for debugging within goland ` \
  --volume "${GIT_CONF}:/volume/gitconfig" \
  --volume "${GOLAND_CONF}:/volume/.GoLand" \
  --volume "${JAVA_CONF}:/volume/.java" \
  --volume "${GOPATH}:/volume/go" \
  ${SSH_CONF_VOLUME} \
  "${IMAGE_NAME}")
echo "${CONTAINER_ID}"
