#!/usr/bin/env bash
#
# Intentionally created to run Clementine audio player from Docker image.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='clementine'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

readonly USER_CONFIG="${HOME}/.config/Clementine"
if [[ ! -e "${USER_CONFIG}" ]]; then
    mkdir --parent "${USER_CONFIG}"
fi

readonly USER_MUSIC="${HOME}/Music"
if [[ ! -e "${USER_MUSIC}" ]]; then
    mkdir --parent "${USER_MUSIC}"
fi

# Enable pulseaudio tcp protocol and propagate pulseaudio server credentials to X11 to connect automatically.
pactl load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 1>/dev/null
pactl load-module module-x11-publish 1>/dev/null

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm -f -v ${CONTAINER_NAME} >/dev/null 2>&1 || true
docker run \
  --device /dev/dri \
  --env DISPLAY \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --env XDG_RUNTIME_DIR \
  --net "host" `# Required to connect pulseaudio` \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume "${USER_CONFIG}":/var/lib/clementine/config \
  --volume "${USER_MUSIC}":/var/lib/clementine/music \
${IMAGE_NAME}
