#!/usr/bin/env bash
#
# Intentionally created to run Clementine audio player from Docker image.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='clementine'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# Pull latest Docker image to have the latest version.
ip r|grep "default\|0.0.0.0" 1>/dev/null && docker pull "${IMAGE_NAME}"

readonly USER_CONFIG="${HOME}/.config/Clementine"
if [[ ! -e "${USER_CONFIG}" ]]; then
    mkdir --parent "${USER_CONFIG}"
    touch "${USER_CONFIG}/Clementine.conf"
    echo -e "[MainWindow]\nkeeprunning=false\n" >> "${USER_CONFIG}/Clementine.conf"
fi

if [[ ! -e "${XDG_RUNTIME_DIR}" ]]; then
    mkdir --parent "${XDG_RUNTIME_DIR}"
fi

readonly USER_MUSIC="${HOME}/Music"
if [[ ! -e "${USER_MUSIC}" ]]; then
    mkdir --parent "${USER_MUSIC}"
fi

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Clementine
cat <<EOH

╔═╗┬  ┌─┐┌┬┐┌─┐┌┐┌┌┬┐┬┌┐┌┌─┐
║  │  ├┤ │││├┤ │││ │ ││││├┤ 
╚═╝┴─┘└─┘┴ ┴└─┘┘└┘ ┴ ┴┘└┘└─┘
${IMAGE_NAME}

========
Volumes:
========
Settings: '${USER_CONFIG}'
Music...: '${USER_MUSIC}'

EOH

# Enable pulse audio TCP server to connect to it.
readonly DOCKER_BRIDGE_IP=$(docker network inspect --format '{{range .IPAM.Config}}{{.Gateway}}{{end}}' bridge)
readonly PULSE_AUDIO_TCP_MODULE='module-native-protocol-tcp'
readonly PULSE_AUDIO_TCP=$(pactl list modules |grep --silent "${PULSE_AUDIO_TCP_MODULE}"; echo $?)
if [[ "$PULSE_AUDIO_TCP" = "1" ]]; then
    pactl load-module "${PULSE_AUDIO_TCP_MODULE}" auth-ip-acl="${DOCKER_BRIDGE_IP}" auth-anonymous=1 1>/dev/null
fi

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
# shared sound usage requires --i
docker rm -f -v ${CONTAINER_NAME} >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --rm \
  --volume /etc/localtime:/etc/localtime:ro \
  `# Audio` \
  --env "PULSE_SERVER=tcp:${DOCKER_BRIDGE_IP}:4713" \
  `# Video` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# Clementine` \
  --env XDG_RUNTIME_DIR \
  --volume "${USER_CONFIG}":/var/lib/clementine/config \
  --volume "${USER_MUSIC}":/var/lib/clementine/music \
  ${IMAGE_NAME})
echo "${CONTAINER_ID}"
