#!/usr/bin/env bash
#
# Runs Docker container as stated below.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='ansible-playbook'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# Pull latest Docker image to have the latest version.
readonly ONLINE=$(ip r|grep "default\|0.0.0.0" 1>/dev/null; echo $?)
if [[ "${ONLINE}" = "0" ]]; then
    docker pull ${IMAGE_NAME}
fi

# Mount local .ssh directory only in case it is present.
# Applies checks to avoid issues with dead symbolic links.
SSH_PATH=""
if [[ -L "${HOME}/.ssh" ]]; then
  readonly possiblePath=$(readlink -f "${HOME}/.ssh")
  if [[ -d "${possiblePath}" ]]; then
    SSH_PATH=$possiblePath
  fi
elif [[ -d "${HOME}/.ssh" ]]; then
  SSH_PATH="${HOME}/.ssh"
fi

SSH_BANNER=""
if [[ ! "${SSH_PATH}" = "" ]]; then
    SSH_Banner="SSH ............: '${SSH_PATH}'"
fi

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Ansible%20Playbook
cat <<EOH

╔═╗┌┐┌┌─┐┬┌┐ ┬  ┌─┐  ╔═╗┬  ┌─┐┬ ┬┌┐ ┌─┐┌─┐┬┌─
╠═╣│││└─┐│├┴┐│  ├┤   ╠═╝│  ├─┤└┬┘├┴┐│ ││ │├┴┐
╩ ╩┘└┘└─┘┴└─┘┴─┘└─┘  ╩  ┴─┘┴ ┴ ┴ └─┘└─┘└─┘┴ ┴
${IMAGE_NAME}

========
Volumes:
========
${SSH_BANNER}

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

SSH_CONF_VOLUME=""
if [[ ! "${SSH_PATH}" = "" ]]; then
  SSH_CONF_VOLUME="--volume ${SSH_PATH}:/volume/.ssh"
fi

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run \
  --tty \
  --interactive \
  --rm \
  --env GIVEN_GROUP="$(id -gn "${USER}")" \
  --env GIVEN_GROUP_ID="$(id -g "${USER}")" \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --volume "${PWD}":/opt \
  --net host \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  ${SSH_CONF_VOLUME} \
  "${IMAGE_NAME}" "$@"
