#!/usr/bin/env bash
#
# Run Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='tor'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Tor
cat <<EOH

╔╦╗┌─┐┬─┐
 ║ │ │├┬┘
 ╩ └─┘┴└─
${IMAGE_NAME}

EOH

docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
docker run \
 --detach=true \
 --name tor \
 --publish 0.0.0.0:9050:9050 \
 suckowbiz/tor "ExcludeExitNodes" "{de},{at},{ch}"
