#!/usr/bin/env bash
#
# Run Intellij Idea Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly IMAGE_NAME='suckowbiz/idea'
readonly CONTAINER_NAME='idea'

readonly GIT_CONFIG="${HOME}/.gitconfig"
mkdir --parent \
  "${PROJECTS_DIR:=${HOME}/IdeaProjects}" \
  "${IDEA_DIR:=${HOME}/.IntelliJIdea}" \
  "${M2_DIR:=${HOME}/.m2}" \
  "${SSH_DIR:=${HOME}/.ssh}" \
  "${JAVA_DIR:=${HOME}/.java}" || true

# http://patorjk.com/software/taag/#p=display&f=Doom&t=Running%20Idea...
cat <<"END-OF-HEREDOC"

______                  _               _____    _
| ___ \                (_)             |_   _|  | |
| |_/ /   _ _ __  _ __  _ _ __   __ _    | |  __| | ___  __ _
|    / | | | '_ \| '_ \| | '_ \ / _` |   | | / _` |/ _ \/ _` |
| |\ \ |_| | | | | | | | | | | | (_| |  _| || (_| |  __/ (_| |_ _ _
\_| \_\__,_|_| |_|_| |_|_|_| |_|\__, |  \___/\__,_|\___|\__,_(_|_|_)
                                 __/ |
                                |___/

END-OF-HEREDOC

cat <<END-OF-HEREDOC
========
Volumes:
========
Idea Settings ............: '${IDEA_DIR}'
Java Settings ............: '${JAVA_DIR}'
Maven Home ...............: '${M2_DIR}'
Projects .................: '${PROJECTS_DIR}'
SSH Settings .............: '${SSH_DIR}'
Git config ...............: '${GIT_CONFIG}'

END-OF-HEREDOC

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run \
  --detach \
  --env DISPLAY \
  --env GIVEN_GROUP="$(id -gn "${USER}")" \
  --env GIVEN_GROUP_ID="$(id -g "${USER}")" \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume "${GIT_CONFIG}":/opt/.gitconfig \
  --volume "${IDEA_DIR}":/opt/.IntelliJIdea \
  --volume "${JAVA_DIR}":/opt/.java \
  --volume "${M2_DIR}":/opt/.m2 \
  --volume "${PROJECTS_DIR}":/opt/IdeaProjects \
  --volume "${SSH_DIR}":/opt/.ssh:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  ${IMAGE_NAME}
