#!/usr/bin/env bash
#
# Intentionally created to run Google Chrome Browser from Docker image.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='skype-legacy'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

readonly DEV_VIDEO=$(test -e /dev/video0 && echo "--device /dev/video0" || echo "")
readonly SKYPE_DBPATH="${HOME}/.Skype"
if [[ ! -e "${SKYPE_DBPATH}" ]]; then
    mkdir --parent "${SKYPE_DBPATH}"
fi

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Skype%20Legacy
cat <<EOH

╔═╗┬┌─┬ ┬┌─┐┌─┐  ╦  ┌─┐┌─┐┌─┐┌─┐┬ ┬
╚═╗├┴┐└┬┘├─┘├┤   ║  ├┤ │ ┬├─┤│  └┬┘
╚═╝┴ ┴ ┴ ┴  └─┘  ╩═╝└─┘└─┘┴ ┴└─┘ ┴ 
https://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
# shellcheck disable=SC2006,SC2046
docker run \
  --detach \
  --device /dev/snd \
    -v /etc/machine-id:/etc/machine-id \
    -v /run/user/${UID}/pulse:/run/user/${UID}/pulse \
    -v /var/lib/dbus:/var/lib/dbus \
    -v ~/.pulse:/home/${USER}/.pulse \
  ${DEV_VIDEO} \
  --env DISPLAY \
  --env XDG_RUNTIME_DIR \
  --privileged \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --ipc=host \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume "${SKYPE_DBPATH}:/Skype" \
  "${IMAGE_NAME}"
