#!/usr/bin/env bash
#
# Run GIMP Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='gimp'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"
readonly USER_PICTURES="${HOME}/Pictures"
if [[ ! -e "${USER_PICTURES}" ]]; then
    mkdir --parent "${USER_PICTURES}"
fi

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Gimp
cat <<EOH

╔═╗┬┌┬┐┌─┐
║ ╦││││├─┘
╚═╝┴┴ ┴┴  
${IMAGE_NAME}

=========
Volumes:
=========
Pictures: '${USER_PICTURES}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  `# Audio` \
  --env "PULSE_SERVER=tcp:${DOCKER_BRIDGE_IP}:4713" \
  `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# Gimp` \
  --volume "${USER_PICTURES}":/var/lib/gimp/pictures \
  ${IMAGE_NAME} "$@")
echo "${CONTAINER_ID}"
