#!/usr/bin/env bash
#
# Run GIMP Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly IMAGE_NAME='suckowbiz/gimp'
readonly CONTAINER_NAME='gimp'

# parse command line arguments to grap extra information
while getopts haw: opt
do
  case $opt in
    h)  echo "Use with '-w' to set your GIMP_WORKDIR path."
        echo "Example: './gimp -w /home/tobias/GIMP_WORKDIR'"
        exit 0
        ;;
    w)	GIMP_WORKDIR=$OPTARG
    	;;
    \?) exit 1
        ;;
  esac
done
echo -e "Mounting GIMP_WORKDIR: '${GIMP_WORKDIR:=${HOME}/Pictures}'.\nTry './gimp -h' for more information .."

mkdir -p ${GIMP_WORKDIR}

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm -f -v ${CONTAINER_NAME} >/dev/null 2>&1 || true
docker run \
  --detach \
  --env DISPLAY=${DISPLAY} \
  --env GIVEN_GROUP=$(id -gn ${USER}) \
  --env GIVEN_GROUP_ID=$(id -g ${USER}) \
  --env GIVEN_USER=${USER} \
  --env GIVEN_USER_ID=${UID} \
  --hostname ${CONTAINER_NAME} \
  --name ${CONTAINER_NAME} \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume ${GIMP_WORKDIR}:/Pictures \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  ${IMAGE_NAME}
