#!/usr/bin/env bash
#
# Run GIMP Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='gimp'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"
readonly USER_PICTURES="${HOME}/Pictures"
if [[ ! -e "${USER_PICTUES}" ]]; then
    mkdir --parent "${USER_PICTURES}"
fi

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
docker run \
  --detach \
  --env DISPLAY \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume "${USER_PICTURES}":/var/lib/gimp/pictures \
  ${IMAGE_NAME} "$@"
