#!/usr/bin/env bash
#
# Intentionally created to run Google Chrome Browser from Docker image.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='chrome'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

readonly USER_DOWNLOAD_DIR="${HOME}/Downloads"
test -e "${USER_DOWNLOAD_DIR}" || mkdir --parent "${USER_DOWNLOAD_DIR}"

readonly USER_DATA_DIR="${HOME}/.config/google-chrome"
test -e "${USER_DATA_DIR}" || mkdir --parent "${USER_DATA_DIR}"

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run \
  --cap-add SYS_ADMIN `# Enable privilege to utilize PID namespace features required by chrome. (see man clone)` \
  --detach \
  --device /dev/dri `# Direct GPU access improves gfx rendering to avoid fail e.g. on google maps usage.` \
  --device /dev/snd \
  --env DISPLAY \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --net "host" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume "${USER_DATA_DIR}":/var/lib/chrome/data \
  --volume "${USER_DOWNLOAD_DIR}":/var/lib/chrome/downloads \
  "${IMAGE_NAME}" "$@"
