#!/usr/bin/env bash
#
# Intentionally created to run Google Chrome Browser from Docker image.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='chrome'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

readonly USER_DOWNLOAD_DIR="${HOME}/Downloads"
if [[ ! -e "${USER_DOWNLOAD_DIR}" ]]; then
    mkdir --parent "${USER_DOWNLOAD_DIR}"
fi

readonly USER_DATA_DIR="${HOME}/.config/google-chrome"
if [[ ! -e "${USER_DATA_DIR}" ]]; then
    mkdir --parent "${USER_DATA_DIR}"
fi

readonly DEV_VIDEO=$(test -e /dev/video0 && echo "--device /dev/video0" || echo "")

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Google%20Chrome
cat <<EOH

╔═╗┌─┐┌─┐┌─┐┬  ┌─┐  ╔═╗┬ ┬┬─┐┌─┐┌┬┐┌─┐
║ ╦│ ││ ││ ┬│  ├┤   ║  ├─┤├┬┘│ ││││├┤ 
╚═╝└─┘└─┘└─┘┴─┘└─┘  ╚═╝┴ ┴┴└─└─┘┴ ┴└─┘
${IMAGE_NAME}

=========
Volumes:
=========
Downloads: '${USER_DOWNLOAD_DIR}'
Settings.: '${USER_DATA_DIR}'

EOH

# Enable pulse audio TCP server to connect to it.
readonly DOCKER_BRIDGE_IP='172.17.0.1'
readonly PULSE_AUDIO_TCP_MODULE='module-native-protocol-tcp'
readonly PULSE_AUDIO_TCP=$(pactl list modules |grep --silent "${PULSE_AUDIO_TCP_MODULE}"; echo $?)
if [[ "$PULSE_AUDIO_TCP" = "1" ]]; then
    pactl load-module "${PULSE_AUDIO_TCP_MODULE}" auth-ip-acl="${DOCKER_BRIDGE_IP}" auth-anonymous=1 1>/dev/null
fi

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
# shellcheck disable=SC2006,SC2046,SC2086
#   --ipc=host \
docker run \
  --cap-add SYS_ADMIN `# Enable privilege to utilize PID namespace features required by chrome. (see man clone)` \
  --detach \
  --device /dev/dri `# Direct GPU access improves gfx rendering to avoid fail e.g. on google maps usage.` \
  ${DEV_VIDEO} \
  --env "PULSE_SERVER=tcp:${DOCKER_BRIDGE_IP}:4713" `#using /dev/snd in compbination with ipc=host failed the hosts sound!` \
  --env DISPLAY \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume "${USER_DATA_DIR}":/var/lib/chrome/data \
  --volume "${USER_DOWNLOAD_DIR}":/var/lib/chrome/downloads \
  "${IMAGE_NAME}" "--incognito"
