#!/usr/bin/env bash
#
# Intentionally created to run Calibre e-book manager from Docker image.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='calibre'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# Pull latest Docker image to have the latest version.
#readonly ONLINE=$(ip r|grep "default\|0.0.0.0" 1>/dev/null; echo $?)
#if [[ "${ONLINE}" = "0" ]]; then
#    docker pull ${IMAGE_NAME}
#fi

readonly RUNNING_CONTAINER_ID=$(docker ps --quiet --filter "name=${CONTAINER_NAME}")
[[ "${RUNNING_CONTAINER_ID}" = "" ]] || exit

readonly CALIBRE_CONFIG="${HOME}/.config/calibre"
if [[ ! -e "${CALIBRE_CONFIG}" ]]; then
    mkdir --parent "${CALIBRE_CONFIG}"
fi

readonly CALIBRE_LIB="${HOME}/Calibre Library"
if [[ ! -e "${CALIBRE_LIB}" ]]; then
    mkdir --parent "${CALIBRE_LIB}"
fi

readonly DEV_VIDEO=$(test -e /dev/video0 && echo "--device /dev/video0" || echo "")

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Calibre
cat <<EOH

╔═╗┌─┐┬  ┬┌┐ ┬─┐┌─┐
║  ├─┤│  │├┴┐├┬┘├┤ 
╚═╝┴ ┴┴─┘┴└─┘┴└─└─┘
${IMAGE_NAME}

========
Volumes:
========
Config.: '${CALIBRE_CONFIG}'
Library: '${CALIBRE_LIB}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true

# shellcheck disable=SC2006,SC2046,SC2086
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /etc/machine-id:/etc/machine-id:ro \
  `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# Calibre` \
  ${DEV_VIDEO} \
  --volume "${CALIBRE_CONFIG}:/var/lib/calibre/config" \
  --volume "${CALIBRE_LIB}:/var/lib/calibre/Calibre Library" \
  `# DBus` \
  --env DBUS_SESSION_BUS_ADDRESS \
  --security-opt apparmor:unconfined `# Solves: An AppArmor policy prevents this sender from sending this message to this recipient`\
  --volume /var/run/dbus:/var/run/dbus `# Solves: Failed to connect to socket /var/run/dbus/system_bus_socket` \
  --volume /run/user/${UID}/bus:/run/user/${UID}/bus \
  "${IMAGE_NAME}")
echo "${CONTAINER_ID}"
