#!/usr/bin/env bash
#
# Run Steam Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='steam'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"
readonly USER_DATA="${HOME}/Steam"

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Steam
cat <<EOH

╔═╗┌┬┐┌─┐┌─┐┌┬┐
╚═╗ │ ├┤ ├─┤│││
╚═╝ ┴ └─┘┴ ┴┴ ┴

========
Volumes:
========
User Data: '${USER_DATA}'

EOH

if [[ ! -e "${USER_DATA}" ]]; then
    mkdir --parent "${USER_DATA}"
fi

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
docker run \
  --detach \
  --device /dev/dri \
  --device /dev/snd \
  --env DISPLAY \
  --env GIVEN_GROUP="$(id -gn "${USER}")" \
  --env GIVEN_GROUP_ID="$(id -g "${USER}")" \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --ipc=host `# Added to enable shared sound` \
  --net host \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume "${USER_DATA}":/var/lib/steam \
  ${IMAGE_NAME}
