#!/usr/bin/env bash
#
# Run Intellij WebStorm in a Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly IMAGE_NAME='suckowbiz/webstorm'
readonly CONTAINER_NAME='webstorm'

readonly BASE_CONF="${HOME}/.config"
mkdir --parent \
  "${GIT_CONF:=${BASE_CONF}/WebStorm/gitconfig}" \
  "${WORKDIR:=${HOME}/WebStorm}" \
  "${WEBSTORM_CONF:=${BASE_CONF}/WebStorm}" \
  "${JAVA_CONF:=${BASE_CONF}/WebStorm/java}" || true
touch ${GIT_CONF}/.gitconfig

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=WebStorm
cat <<EOH

╦ ╦┌─┐┌┐ ╔═╗┌┬┐┌─┐┬─┐┌┬┐
║║║├┤ ├┴┐╚═╗ │ │ │├┬┘│││
╚╩╝└─┘└─┘╚═╝ ┴ └─┘┴└─┴ ┴
$IMAGE_NAME

========
Volumes:
========
WebStorm Conf.....: '${WEBSTORM_CONF}'
WebStorm Java Conf: '${JAVA_CONF}'
Workdir ..........: '${WORKDIR}'
Git Conf..........: '${GIT_CONF}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
#  --net=host \
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# WebStorm` \
  --volume "${GIT_CONF}:/volume/gitconfig" \
  --volume "${WEBSTORM_CONF}:/volume/.WebStorm" \
  --volume "${JAVA_CONF}:/volume/.java" \
  --volume "${WORKDIR}:/volume/workdir" \
  "${IMAGE_NAME}")
echo "${CONTAINER_ID}"
