#!/usr/bin/env bash
#
# Runs Docker container as stated below.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

remote_directory=${1////-}
remote_directory=${remote_directory/:/}
readonly CONTAINER_NAME="nfs-hub-${remote_directory}"
readonly IMAGE_NAME="suckowbiz/nfs-hub"
readonly NAMED_VOLUME="/nfs"

docker rm --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run \
  --detach \
  --env NFS_URI="$1" \
  --env NFS_DOMAIN="$2" \
  --env NFS_UID="$3" \
  --env NFS_GID="$4" \
  --env GIVEN_GID="$(id -g "${USER}")" \
  --env GIVEN_UID="${UID}" \
  --name "${CONTAINER_NAME}" \
  --env GIVEN_USER="${USER}" \
  --tty \
  --volume "$5":"${NAMED_VOLUME}":shared \
  --cap-add SYS_ADMIN \
  --device /dev/fuse \
  --security-opt apparmor:unconfined \
  "${IMAGE_NAME}" "$@"
