#!/usr/bin/env bash
#
# Runs Docker container as stated below.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='ansible-node'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run \
  --detach \
  --name "${CONTAINER_NAME}" \
  --publish "8022:22" \
  --volume /etc/localtime:/etc/localtime:ro \
  "${IMAGE_NAME}" "$@"
