#!/usr/bin/env bash
#
# Run Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='supertux'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"
readonly USER_DATA="${HOME}/.config/supertux2"

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=SuperTux
cat <<EOH

╔═╗┬ ┬┌─┐┌─┐┬─┐╔╦╗┬ ┬─┐ ┬
╚═╗│ │├─┘├┤ ├┬┘ ║ │ │┌┴┬┘
╚═╝└─┘┴  └─┘┴└─ ╩ └─┘┴ └─
${IMAGE_NAME}

========
Volumes:
========
User Data.: '${USER_DATA}'

EOH

if [[ ! -e "${USER_DATA}" ]]; then
    mkdir --parent "${USER_DATA}"
fi

# Enable pulse audio TCP server to connect to it.
readonly DOCKER_BRIDGE_IP='172.17.0.1'
readonly PULSE_AUDIO_TCP_MODULE='module-native-protocol-tcp'
readonly PULSE_AUDIO_TCP=$(pactl list modules |grep --silent "${PULSE_AUDIO_TCP_MODULE}"; echo $?)
if [[ "$PULSE_AUDIO_TCP" = "1" ]]; then
    pactl load-module "${PULSE_AUDIO_TCP_MODULE}" auth-ip-acl="${DOCKER_BRIDGE_IP}" auth-anonymous=1 1>/dev/null
fi

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  `# Audio` \
  --env "PULSE_SERVER=tcp:${DOCKER_BRIDGE_IP}:4713" \
  `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# Supertux` \
  --volume "${USER_DATA}":/var/lib/supertux2 \
  ${IMAGE_NAME})
echo "${CONTAINER_ID}"
