#!/usr/bin/env bash
#
# Run Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='unifi'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# Pull latest Docker image to have the latest version.
ip r|grep "default\|0.0.0.0" 1>/dev/null && docker pull "${IMAGE_NAME}"

readonly UNIFI_DATA_DIR="${HOME}/.config/unifi/data"
if [[ ! -e "${UNIFI_DATA_DIR}" ]]; then
    mkdir --parent "${UNIFI_DATA_DIR}"
    chmod 777 "${UNIFI_DATA_DIR}"
fi

readonly UNIFI_LOG_DIR="${HOME}/.config/unifi/log"
if [[ ! -e "${UNIFI_LOG_DIR}" ]]; then
    mkdir --parent "${UNIFI_LOG_DIR}"
    chmod 777 "${UNIFI_LOG_DIR}"
fi

readonly UNIFI_RUN_DIR="${HOME}/.config/unifi/run"
if [[ ! -e "${UNIFI_RUN_DIR}" ]]; then
    mkdir --parent "${UNIFI_RUN_DIR}"
    chmod 777 "${UNIFI_RUN_DIR}"
fi

# http://patorjk.com/software/taag/#p=display&f=Calvin%20S&t=Unifi
cat <<EOH

╦ ╦┌┐┌┬╔═╗┬  ╔╗╔┌─┐┌┬┐┬ ┬┌─┐┬─┐┬┌─  ╔═╗┌─┐┌─┐┬  ┬┌─┐┌─┐┌┬┐┬┌─┐┌┐┌
║ ║││││╠╣ │  ║║║├┤  │ ││││ │├┬┘├┴┐  ╠═╣├─┘├─┘│  ││  ├─┤ │ ││ ││││
╚═╝┘└┘┴╚  ┴  ╝╚╝└─┘ ┴ └┴┘└─┘┴└─┴ ┴  ╩ ╩┴  ┴  ┴─┘┴└─┘┴ ┴ ┴ ┴└─┘┘└┘
${IMAGE_NAME}

========
Volumes:
========
UNIFI DATA ...: ${UNIFI_DATA_DIR}
UNIFI LOG ....: ${UNIFI_LOG_DIR}
UNIFI RUN ....: ${UNIFI_RUN_DIR}

###############################
Web GUI: https://localhost:8443
###############################

Note: If a supported UniFi device is not listed within the application, it may be
      required to re-register it. See example below.

Example - Register UAC-AP-Pro Access Point

  # First log in into the access point device:
  >_ ssh ubnt@<device-ip>
  # On the access point run:
  >_ set-inform http://<network-application-ip>:8080/inform

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --rm \
  --volume "${UNIFI_DIR}":/usr/lib/unifi \
  --volume "${UNIFI_DATA_DIR}":/var/lib/unifi \
  --volume "${UNIFI_LOG_DIR}":/var/log/unifi \
  --volume "${UNIFI_RUN_DIR}":/var/run/unifi \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  --publish 8880:8880 \
  --publish 8843:8843 \
  --publish 6789:6789 \
  --publish 5656-5699:5656-5699 \
  --publish 1001:1001 \
  --publish 1900:1900 \
  --publish 3478:3478 \
  --publish 8080:8080 \
  --publish 8443:8443 \
  --publish 443:443 \
  --publish 8883:8883 \
  --privileged \
  --env UNIFI_USER=${USER} \
  ${IMAGE_NAME})
echo "${CONTAINER_ID}"
