FROM suckowbiz/base

MAINTAINER Tobias Suckow <tobias@suckow.biz>

RUN apt-get --quiet update \
 && apt-get --quiet --assume-yes --no-install-recommends install \
    build-essential \
    libcurl4-openssl-dev

