#!/usr/bin/env bash
#
# Intentionally created to run Pixum Software from Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='pixum'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

readonly USER_PICTURES_DIR="${HOME}/Pictures"
if [[ ! -e "${USER_PICTURES_DIR}" ]]; then
    mkdir --parent "${USER_PICTURES_DIR}"
fi

readonly CEWE_DIR="${HOME}/.config/CeWe Color"
if [[ ! -e "${CEWE_DIR}" ]]; then
    mkdir --parent "${CEWE_DIR}"
fi

readonly MCF_DIR="${HOME}/.mcf"
if [[ ! -e "${MCF_DIR}" ]]; then
    mkdir --parent "${MCF_DIR}"
fi

readonly QT_DIR="${HOME}/.QtWebEngineProcess"
if [[ ! -e "${QT_DIR}" ]]; then
    mkdir --parent "${QT_DIR}"
fi

readonly PIXUM_CONFIG_DIR="${HOME}/.Pixum Fotowelt"
if [[ ! -e "${PIXUM_CONFIG_DIR}" ]]; then
    mkdir --parent "${PIXUM_CONFIG_DIR}"
fi

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Pixum%20Fotowelt%20Software
cat <<EOH

╔═╗┬─┐ ┬┬ ┬┌┬┐  ╔═╗┌─┐┌┬┐┌─┐┬ ┬┌─┐┬  ┌┬┐  ╔═╗┌─┐┌─┐┌┬┐┬ ┬┌─┐┬─┐┌─┐
╠═╝│┌┴┬┘│ ││││  ╠╣ │ │ │ │ ││││├┤ │   │   ╚═╗│ │├┤  │ │││├─┤├┬┘├┤ 
╩  ┴┴ └─└─┘┴ ┴  ╚  └─┘ ┴ └─┘└┴┘└─┘┴─┘ ┴   ╚═╝└─┘└   ┴ └┴┘┴ ┴┴└─└─┘
${IMAGE_NAME}

=========
Volumes:
=========
CEWE....: '${CEWE_DIR}'
MCF.....: '${MCF_DIR}'
Pictures: '${USER_PICTURES_DIR}'
Pixum...: '${PIXUM_CONFIG_DIR}'
QT......: '${QT_DIR}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true
# shellcheck disable=SC2006,SC2046
docker run \
  --detach \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID=${UID} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume "${CEWE_DIR}":/data/pixum/cewe \
  --volume "${MCF_DIR}":/data/pixum/mcf \
  --volume "${QT_DIR}":/data/pixum/qt \
  --volume "${PIXUM_CONFIG_DIR}":/data/pixum/config \
  --volume "${USER_PICTURES_DIR}":/data/pictures \
  "${IMAGE_NAME}"
