#!/usr/bin/env bash
#
# Intentionally created to run Sweet Home 3D from Docker image.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='sweethome3d'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# Pull latest Docker image to have the latest version.
#ip r|grep "default\|0.0.0.0" 1>/dev/null && docker pull "${IMAGE_NAME}"

readonly RUNNING_CONTAINER_ID=$(docker ps --quiet --filter "name=${CONTAINER_NAME}")
[[ "${RUNNING_CONTAINER_ID}" = "" ]] || exit

readonly USER_DATA_DIR="${HOME}/Downloads"
if [[ ! -e "${USER_DATA_DIR}" ]]; then
    mkdir --parent "${USER_DATA_DIR}"
fi

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=Sweet%20Home%203D
cat <<EOH


╔═╗┬ ┬┌─┐┌─┐┌┬┐  ╦ ╦┌─┐┌┬┐┌─┐  ╔╦╗
╚═╗│││├┤ ├┤  │   ╠═╣│ ││││├┤   3║║
╚═╝└┴┘└─┘└─┘ ┴   ╩ ╩└─┘┴ ┴└─┘  ═╩╝
${IMAGE_NAME}

========
Volumes:
========
Data Exchange: '${USER_DATA_DIR}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true

# shellcheck disable=SC2006,SC2046,SC2086
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /etc/machine-id:/etc/machine-id:ro \
  `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# SweetHome3D` \
  ${DEV_VIDEO} \
  --volume "${USER_DATA_DIR}":/var/lib/sh3d \
  "${IMAGE_NAME}")
echo "${CONTAINER_ID}"
