---
name: CI

on:
 push:
   branches:
     - master
 schedule:
   - cron: '0 0 */2 * *'

jobs:
  # Mainly following: https://docs.github.com/en/actions/guides/publishing-docker-images
  build-and-push:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo to have $GITHUB_WORKSPACE filled with files
        uses: actions/checkout@v3
      -
        name: Log in to Docker Hub to be able to push Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: ansible base
        uses: docker/build-push-action@v3
        env:
          IMAGE: ansible-base
        with:
          context: "${{ github.workspace }}/ansible/base"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: ansible control
        uses: docker/build-push-action@v3
        env:
          IMAGE: ansible-control
        with:
          context: "${{ github.workspace }}/ansible/control"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: ansible playbook
        uses: docker/build-push-action@v3
        env:
          IMAGE: ansible-playbook
        with:
          context: "${{ github.workspace }}/ansible/playbook"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: ansible vault
        uses: docker/build-push-action@v3
        env:
          IMAGE: ansible-vault
        with:
          context: "${{ github.workspace }}/ansible/vault"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: chrome
        uses: docker/build-push-action@v3
        env:
          IMAGE: chrome
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: gimp
        uses: docker/build-push-action@v3
        env:
          IMAGE: gimp
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: goland
        uses: docker/build-push-action@v3
        env:
          IMAGE: goland
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: clementine
        uses: docker/build-push-action@v3
        env:
          IMAGE: clementine
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: keepass2
        uses: docker/build-push-action@v3
        env:
          IMAGE: keepass2
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: logster
        uses: docker/build-push-action@v3
        env:
          IMAGE: logster
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: caddy
        uses: docker/build-push-action@v3
        env:
          IMAGE: caddy
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: tor
        uses: docker/build-push-action@v3
        env:
          IMAGE: tor
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: sweethome3d
        uses: docker/build-push-action@v3
        env:
          IMAGE: sweethome3d
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
      -
        name: code
        uses: docker/build-push-action@v3
        env:
          IMAGE: code
        with:
          context: "${{ github.workspace }}/${{ env.IMAGE }}"
          push: true
          tags: "suckowbiz/${{ env.IMAGE }}:latest"
