#!/usr/bin/env bash
#
# Run KeePass2 Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='keepass2'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

# Pull latest Docker image to have the latest version.
ip r|grep "default\|0.0.0.0" 1>/dev/null && docker pull "${IMAGE_NAME}"

readonly KEEPASS_DATA="${HOME}/KeePass"
if [[ ! -e "${KEEPASS_DATA}" ]]; then
    mkdir --parent "${KEEPASS_DATA}"
fi

readonly KEEPASS_CONFIG="${HOME}/.config/KeePass"
if [[ ! -e "${KEEPASS_CONFIG}" ]]; then
    mkdir --parent "${KEEPASS_CONFIG}"
fi

# http://patorjk.com/software/taag/#p=display&f=Doom&t=Running%20KeePass2 
cat <<EOH

╦╔═┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐
╠╩╗├┤ ├┤ ├─┘├─┤└─┐└─┐
╩ ╩└─┘└─┘┴  ┴ ┴└─┘└─┘
${IMAGE_NAME}

========
Volumes:
========
Settings............: '${KEEPASS_DATA}'
Database............: '${KEEPASS_CONFIG}'

EOH

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
readonly CONTAINER_ID=$(docker run \
  --detach \
  --hostname ${CONTAINER_NAME} \
  --name "${CONTAINER_NAME}" \
  --volume /etc/localtime:/etc/localtime:ro \
    `# Video` \
  --device /dev/dri `# Direct GPU access improves gfx rendering.` \
  --env DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  `# Entrypoint` \
  --env GIVEN_GROUP=$(id -gn "${USER}") \
  --env GIVEN_GROUP_ID=$(id -g "${USER}") \
  --env GIVEN_USER="${USER}" \
  --env GIVEN_USER_ID="${UID}" \
  `# Keepass` \
  --volume "${KEEPASS_DATA}":/var/lib/keepass2/data \
  --volume "${KEEPASS_CONFIG}":/var/lib/keepass2/config \
  ${IMAGE_NAME})
echo "${CONTAINER_ID}"