#!/usr/bin/env bash
#
# Run KeePass2 Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly CONTAINER_NAME='keepass2'
readonly IMAGE_NAME="suckowbiz/${CONTAINER_NAME}"

readonly KEEPASS_DATA="${HOME}/KeePass"
test -e "${KEEPASS_DATA}" || mkdir --parent "${KEEPASS_DATA}"

readonly KEEPASS_CONFIG="${HOME}/.config/KeePass"
test -e "${KEEPASS_CONFIG}" || mkdir --parent "${KEEPASS_CONFIG}"

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

# removing previous existing containers to enable start up
docker rm --force --volumes ${CONTAINER_NAME} >/dev/null 2>&1 || true
docker run \
  --detach \
  --env DISPLAY=${DISPLAY} \
  --env GIVEN_GROUP=$(id -gn ${USER}) \
  --env GIVEN_GROUP_ID=$(id -g ${USER}) \
  --env GIVEN_USER=${USER} \
  --env GIVEN_USER_ID=${UID} \
  --hostname ${CONTAINER_NAME} \
  --name ${CONTAINER_NAME} \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume "${KEEPASS_DATA}":/var/lib/keepass2/data \
  --volume "${KEEPASS_CONFIG}":/var/lib/keepass2/config \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  ${IMAGE_NAME}
