#!/usr/bin/env bash
#
# Run KeePass2 Docker container.
# (follows https://google.github.io/styleguide/shell.xml)
set -e

readonly IMAGE_NAME='suckowbiz/keepass2'
readonly CONTAINER_NAME='keepass2'

# enable passing display to be able to run any GUI
xhost +local:root > /dev/null 2>&1

readonly KEEPASS_DATA=${HOME}/KeePass
readonly KEEPASS_CONFIG=${HOME}/.config/KeePass
mkdir -p $KEEPASS_CONFIG $KEEPASS_DATA

# removing previous existing containers to enable start up
docker rm -f -v ${CONTAINER_NAME} >/dev/null 2>&1 || true
docker run \
  --detach \
  --env DISPLAY=${DISPLAY} \
  --env GIVEN_GROUP=$(id -gn ${USER}) \
  --env GIVEN_GROUP_ID=$(id -g ${USER}) \
  --env GIVEN_USER=${USER} \
  --env GIVEN_USER_ID=${UID} \
  --hostname ${CONTAINER_NAME} \
  --name ${CONTAINER_NAME} \
  --volume $KEEPASS_DATA:/opt/KeePass2/data \
  --volume $KEEPASS_CONFIG:/opt/KeePass2/config \
  --volume /etc/localtime:/etc/localtime:ro \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  ${IMAGE_NAME}
